/* tslint:disable */
/* eslint-disable */
/**
 * amber
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FieldDef
 */
export interface FieldDef {
    [key: string]: object | any;
    /**
     * 
     * @type {string}
     * @memberof FieldDef
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof FieldDef
     */
    tableID: number;
    /**
     * 
     * @type {number}
     * @memberof FieldDef
     */
    columnID: number;
    /**
     * 
     * @type {number}
     * @memberof FieldDef
     */
    dataTypeID: number;
    /**
     * 
     * @type {number}
     * @memberof FieldDef
     */
    dataTypeSize: number;
    /**
     * 
     * @type {number}
     * @memberof FieldDef
     */
    dataTypeModifier: number;
    /**
     * 
     * @type {string}
     * @memberof FieldDef
     */
    format: string;
}

export function FieldDefFromJSON(json: any): FieldDef {
    return FieldDefFromJSONTyped(json, false);
}

export function FieldDefFromJSONTyped(json: any, ignoreDiscriminator: boolean): FieldDef {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'name': json['name'],
        'tableID': json['tableID'],
        'columnID': json['columnID'],
        'dataTypeID': json['dataTypeID'],
        'dataTypeSize': json['dataTypeSize'],
        'dataTypeModifier': json['dataTypeModifier'],
        'format': json['format'],
    };
}

export function FieldDefToJSON(value?: FieldDef | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'name': value.name,
        'tableID': value.tableID,
        'columnID': value.columnID,
        'dataTypeID': value.dataTypeID,
        'dataTypeSize': value.dataTypeSize,
        'dataTypeModifier': value.dataTypeModifier,
        'format': value.format,
    };
}


