/* tslint:disable */
/* eslint-disable */
/**
 * amber
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetTagBody
 */
export interface GetTagBody {
    /**
     * 
     * @type {object}
     * @memberof GetTagBody
     */
    id: object;
}

export function GetTagBodyFromJSON(json: any): GetTagBody {
    return GetTagBodyFromJSONTyped(json, false);
}

export function GetTagBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTagBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function GetTagBodyToJSON(value?: GetTagBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


