/* tslint:disable */
/* eslint-disable */
/**
 * amber
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TagFilter
 */
export interface TagFilter {
    [key: string]: object | any;
    /**
     * 
     * @type {Array<any>}
     * @memberof TagFilter
     */
    resourceIds?: Array<any>;
    /**
     * 
     * @type {boolean}
     * @memberof TagFilter
     */
    includeDeleted?: boolean;
}

export function TagFilterFromJSON(json: any): TagFilter {
    return TagFilterFromJSONTyped(json, false);
}

export function TagFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagFilter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'resourceIds': !exists(json, 'resourceIds') ? undefined : json['resourceIds'],
        'includeDeleted': !exists(json, 'includeDeleted') ? undefined : json['includeDeleted'],
    };
}

export function TagFilterToJSON(value?: TagFilter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'resourceIds': value.resourceIds,
        'includeDeleted': value.includeDeleted,
    };
}


