version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    docker:
      - image: 'cimg/base:stable'
    steps: 
      - run: npm run lint
workflows:
  node-tests:
    jobs:
      - test 
      
