version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    docker:
      - image: circleci/node@3.0.0
    steps: 
      - run: node --version
      - run: npm run lint
workflows:
  node-tests:
    jobs:
      - test 
      
