/* tslint:disable */
/* eslint-disable */
/**
 * amber
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    QueryResultAny,
    QueryResultAnyFromJSON,
    QueryResultAnyToJSON,
    Tag,
    TagFromJSON,
    TagToJSON,
} from '../models';

/**
 * 
 */
export class TagsApi extends runtime.BaseAPI {

    /**
     */
    async deleteTagRaw(): Promise<runtime.ApiResponse<boolean>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/tags/delete`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async deleteTag(): Promise<boolean> {
        const response = await this.deleteTagRaw();
        return await response.value();
    }

    /**
     */
    async getTagRaw(): Promise<runtime.ApiResponse<Tag>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/tags/get`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => TagFromJSON(jsonValue));
    }

    /**
     */
    async getTag(): Promise<Tag> {
        const response = await this.getTagRaw();
        return await response.value();
    }

    /**
     */
    async getTagsByFilterRaw(): Promise<runtime.ApiResponse<Array<Tag>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/tags/get-by`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TagFromJSON));
    }

    /**
     */
    async getTagsByFilter(): Promise<Array<Tag>> {
        const response = await this.getTagsByFilterRaw();
        return await response.value();
    }

    /**
     */
    async updateOrCreateTagRaw(): Promise<runtime.ApiResponse<QueryResultAny>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/tags/update`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => QueryResultAnyFromJSON(jsonValue));
    }

    /**
     */
    async updateOrCreateTag(): Promise<QueryResultAny> {
        const response = await this.updateOrCreateTagRaw();
        return await response.value();
    }

}
