/* tslint:disable */
/* eslint-disable */
/**
 * amber
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Guid,
    GuidFromJSON,
    GuidFromJSONTyped,
    GuidToJSON,
} from './';

/**
 * 
 * @export
 * @interface AssemblyFilter
 */
export interface AssemblyFilter {
    /**
     * 
     * @type {Array<Guid>}
     * @memberof AssemblyFilter
     */
    assemblyStepIds?: Array<Guid>;
    /**
     * 
     * @type {boolean}
     * @memberof AssemblyFilter
     */
    includeDeleted?: boolean;
}

export function AssemblyFilterFromJSON(json: any): AssemblyFilter {
    return AssemblyFilterFromJSONTyped(json, false);
}

export function AssemblyFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssemblyFilter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'assemblyStepIds': !exists(json, 'AssemblyStepIds') ? undefined : ((json['AssemblyStepIds'] as Array<any>).map(GuidFromJSON)),
        'includeDeleted': !exists(json, 'includeDeleted') ? undefined : json['includeDeleted'],
    };
}

export function AssemblyFilterToJSON(value?: AssemblyFilter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'AssemblyStepIds': value.assemblyStepIds === undefined ? undefined : ((value.assemblyStepIds as Array<any>).map(GuidToJSON)),
        'includeDeleted': value.includeDeleted,
    };
}


