/* tslint:disable */
/* eslint-disable */
/**
 * amber
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Guid,
    GuidFromJSON,
    GuidFromJSONTyped,
    GuidToJSON,
} from './';

/**
 * 
 * @export
 * @interface AssemblyStepFilter
 */
export interface AssemblyStepFilter {
    /**
     * 
     * @type {Array<Guid>}
     * @memberof AssemblyStepFilter
     */
    assemblyIds?: Array<Guid>;
    /**
     * 
     * @type {boolean}
     * @memberof AssemblyStepFilter
     */
    includeDeleted?: boolean;
}

export function AssemblyStepFilterFromJSON(json: any): AssemblyStepFilter {
    return AssemblyStepFilterFromJSONTyped(json, false);
}

export function AssemblyStepFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssemblyStepFilter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'assemblyIds': !exists(json, 'assemblyIds') ? undefined : ((json['assemblyIds'] as Array<any>).map(GuidFromJSON)),
        'includeDeleted': !exists(json, 'includeDeleted') ? undefined : json['includeDeleted'],
    };
}

export function AssemblyStepFilterToJSON(value?: AssemblyStepFilter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'assemblyIds': value.assemblyIds === undefined ? undefined : ((value.assemblyIds as Array<any>).map(GuidToJSON)),
        'includeDeleted': value.includeDeleted,
    };
}


