/* tslint:disable */
/* eslint-disable */
/**
 * amber
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EnumDay,
    EnumDayFromJSON,
    EnumDayFromJSONTyped,
    EnumDayToJSON,
    Guid,
    GuidFromJSON,
    GuidFromJSONTyped,
    GuidToJSON,
} from './';

/**
 * 
 * @export
 * @interface BusinessHour
 */
export interface BusinessHour {
    /**
     * 
     * @type {number}
     * @memberof BusinessHour
     */
    versionNo: number;
    /**
     * 
     * @type {Guid}
     * @memberof BusinessHour
     */
    id: Guid;
    /**
     * 
     * @type {EnumDay}
     * @memberof BusinessHour
     */
    day: EnumDay;
    /**
     * 
     * @type {Date}
     * @memberof BusinessHour
     */
    startTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof BusinessHour
     */
    endTime?: Date;
    /**
     * 
     * @type {Guid}
     * @memberof BusinessHour
     */
    tagId?: Guid;
    /**
     * 
     * @type {boolean}
     * @memberof BusinessHour
     */
    isOpen?: boolean;
}

export function BusinessHourFromJSON(json: any): BusinessHour {
    return BusinessHourFromJSONTyped(json, false);
}

export function BusinessHourFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessHour {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'versionNo': json['versionNo'],
        'id': GuidFromJSON(json['id']),
        'day': EnumDayFromJSON(json['day']),
        'startTime': !exists(json, 'startTime') ? undefined : (new Date(json['startTime'])),
        'endTime': !exists(json, 'endTime') ? undefined : (new Date(json['endTime'])),
        'tagId': !exists(json, 'tagId') ? undefined : GuidFromJSON(json['tagId']),
        'isOpen': !exists(json, 'isOpen') ? undefined : json['isOpen'],
    };
}

export function BusinessHourToJSON(value?: BusinessHour | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'versionNo': value.versionNo,
        'id': GuidToJSON(value.id),
        'day': EnumDayToJSON(value.day),
        'startTime': value.startTime === undefined ? undefined : (value.startTime.toISOString()),
        'endTime': value.endTime === undefined ? undefined : (value.endTime.toISOString()),
        'tagId': GuidToJSON(value.tagId),
        'isOpen': value.isOpen,
    };
}


