/* tslint:disable */
/* eslint-disable */
/**
 * amber
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Guid,
    GuidFromJSON,
    GuidFromJSONTyped,
    GuidToJSON,
} from './';

/**
 * 
 * @export
 * @interface MaintenanceLogFilter
 */
export interface MaintenanceLogFilter {
    /**
     * 
     * @type {Array<Guid>}
     * @memberof MaintenanceLogFilter
     */
    maintenanceLogStepIds?: Array<Guid>;
    /**
     * 
     * @type {Array<Guid>}
     * @memberof MaintenanceLogFilter
     */
    resourceIds?: Array<Guid>;
    /**
     * 
     * @type {boolean}
     * @memberof MaintenanceLogFilter
     */
    includeDeleted?: boolean;
}

export function MaintenanceLogFilterFromJSON(json: any): MaintenanceLogFilter {
    return MaintenanceLogFilterFromJSONTyped(json, false);
}

export function MaintenanceLogFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaintenanceLogFilter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'maintenanceLogStepIds': !exists(json, 'maintenanceLogStepIds') ? undefined : ((json['maintenanceLogStepIds'] as Array<any>).map(GuidFromJSON)),
        'resourceIds': !exists(json, 'resourceIds') ? undefined : ((json['resourceIds'] as Array<any>).map(GuidFromJSON)),
        'includeDeleted': !exists(json, 'includeDeleted') ? undefined : json['includeDeleted'],
    };
}

export function MaintenanceLogFilterToJSON(value?: MaintenanceLogFilter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'maintenanceLogStepIds': value.maintenanceLogStepIds === undefined ? undefined : ((value.maintenanceLogStepIds as Array<any>).map(GuidToJSON)),
        'resourceIds': value.resourceIds === undefined ? undefined : ((value.resourceIds as Array<any>).map(GuidToJSON)),
        'includeDeleted': value.includeDeleted,
    };
}


