/* tslint:disable */
/* eslint-disable */
/**
 * amber
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Guid,
    GuidFromJSON,
    GuidFromJSONTyped,
    GuidToJSON,
} from './';

/**
 * 
 * @export
 * @interface MaintenanceLog
 */
export interface MaintenanceLog {
    /**
     * 
     * @type {Guid}
     * @memberof MaintenanceLog
     */
    id: Guid;
    /**
     * 
     * @type {Guid}
     * @memberof MaintenanceLog
     */
    resourceId: Guid;
    /**
     * 
     * @type {string}
     * @memberof MaintenanceLog
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof MaintenanceLog
     */
    details: string;
    /**
     * 
     * @type {string}
     * @memberof MaintenanceLog
     */
    timestamp: string;
}

export function MaintenanceLogFromJSON(json: any): MaintenanceLog {
    return MaintenanceLogFromJSONTyped(json, false);
}

export function MaintenanceLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaintenanceLog {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': GuidFromJSON(json['id']),
        'resourceId': GuidFromJSON(json['resourceId']),
        'type': json['type'],
        'details': json['details'],
        'timestamp': json['timestamp'],
    };
}

export function MaintenanceLogToJSON(value?: MaintenanceLog | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': GuidToJSON(value.id),
        'resourceId': GuidToJSON(value.resourceId),
        'type': value.type,
        'details': value.details,
        'timestamp': value.timestamp,
    };
}


