/* tslint:disable */
/* eslint-disable */
/**
 * amber
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Guid,
    GuidFromJSON,
    GuidFromJSONTyped,
    GuidToJSON,
} from './';

/**
 * 
 * @export
 * @interface RecipeFilter
 */
export interface RecipeFilter {
    /**
     * 
     * @type {Array<Guid>}
     * @memberof RecipeFilter
     */
    recipeStepIds?: Array<Guid>;
    /**
     * 
     * @type {boolean}
     * @memberof RecipeFilter
     */
    includeDeleted?: boolean;
}

export function RecipeFilterFromJSON(json: any): RecipeFilter {
    return RecipeFilterFromJSONTyped(json, false);
}

export function RecipeFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeFilter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'recipeStepIds': !exists(json, 'RecipeStepIds') ? undefined : ((json['RecipeStepIds'] as Array<any>).map(GuidFromJSON)),
        'includeDeleted': !exists(json, 'includeDeleted') ? undefined : json['includeDeleted'],
    };
}

export function RecipeFilterToJSON(value?: RecipeFilter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'RecipeStepIds': value.recipeStepIds === undefined ? undefined : ((value.recipeStepIds as Array<any>).map(GuidToJSON)),
        'includeDeleted': value.includeDeleted,
    };
}


