/* tslint:disable */
/* eslint-disable */
/**
 * amber
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Guid,
    GuidFromJSON,
    GuidFromJSONTyped,
    GuidToJSON,
    RecipeReadOnly,
    RecipeReadOnlyFromJSON,
    RecipeReadOnlyFromJSONTyped,
    RecipeReadOnlyToJSON,
} from './';

/**
 * 
 * @export
 * @interface Recipe
 */
export interface Recipe {
    /**
     * 
     * @type {Guid}
     * @memberof Recipe
     */
    id: Guid;
    /**
     * 
     * @type {string}
     * @memberof Recipe
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Recipe
     */
    description: string;
    /**
     * 
     * @type {Array<Guid>}
     * @memberof Recipe
     */
    requirementIds: Array<Guid>;
    /**
     * 
     * @type {RecipeReadOnly}
     * @memberof Recipe
     */
    readOnly: RecipeReadOnly | null;
}

export function RecipeFromJSON(json: any): Recipe {
    return RecipeFromJSONTyped(json, false);
}

export function RecipeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Recipe {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': GuidFromJSON(json['id']),
        'name': json['name'],
        'description': json['description'],
        'requirementIds': ((json['requirementIds'] as Array<any>).map(GuidFromJSON)),
        'readOnly': RecipeReadOnlyFromJSON(json['readOnly']),
    };
}

export function RecipeToJSON(value?: Recipe | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': GuidToJSON(value.id),
        'name': value.name,
        'description': value.description,
        'requirementIds': ((value.requirementIds as Array<any>).map(GuidToJSON)),
        'readOnly': RecipeReadOnlyToJSON(value.readOnly),
    };
}


