/* tslint:disable */
/* eslint-disable */
/**
 * amber
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecipeReadOnly
 */
export interface RecipeReadOnly {
    /**
     * 
     * @type {boolean}
     * @memberof RecipeReadOnly
     */
    isComplete: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RecipeReadOnly
     */
    isScheduled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RecipeReadOnly
     */
    isAssembly: boolean;
    /**
     * 
     * @type {number}
     * @memberof RecipeReadOnly
     */
    endTime: number;
    /**
     * 
     * @type {number}
     * @memberof RecipeReadOnly
     */
    startTime: number;
}

export function RecipeReadOnlyFromJSON(json: any): RecipeReadOnly {
    return RecipeReadOnlyFromJSONTyped(json, false);
}

export function RecipeReadOnlyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeReadOnly {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isComplete': json['isComplete'],
        'isScheduled': json['isScheduled'],
        'isAssembly': json['isAssembly'],
        'endTime': json['endTime'],
        'startTime': json['startTime'],
    };
}

export function RecipeReadOnlyToJSON(value?: RecipeReadOnly | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isComplete': value.isComplete,
        'isScheduled': value.isScheduled,
        'isAssembly': value.isAssembly,
        'endTime': value.endTime,
        'startTime': value.startTime,
    };
}


