/* tslint:disable */
/* eslint-disable */
/**
 * amber
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Guid,
    GuidFromJSON,
    GuidFromJSONTyped,
    GuidToJSON,
} from './';

/**
 * 
 * @export
 * @interface ResourceFilter
 */
export interface ResourceFilter {
    /**
     * 
     * @type {Array<Guid>}
     * @memberof ResourceFilter
     */
    tagIds?: Array<Guid>;
    /**
     * 
     * @type {boolean}
     * @memberof ResourceFilter
     */
    includeDeleted?: boolean;
}

export function ResourceFilterFromJSON(json: any): ResourceFilter {
    return ResourceFilterFromJSONTyped(json, false);
}

export function ResourceFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceFilter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tagIds': !exists(json, 'tagIds') ? undefined : ((json['tagIds'] as Array<any>).map(GuidFromJSON)),
        'includeDeleted': !exists(json, 'includeDeleted') ? undefined : json['includeDeleted'],
    };
}

export function ResourceFilterToJSON(value?: ResourceFilter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tagIds': value.tagIds === undefined ? undefined : ((value.tagIds as Array<any>).map(GuidToJSON)),
        'includeDeleted': value.includeDeleted,
    };
}


