/* tslint:disable */
/* eslint-disable */
/**
 * amber
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceReadonly
 */
export interface ResourceReadonly {
    /**
     * 
     * @type {string}
     * @memberof ResourceReadonly
     */
    tagList: string;
}

export function ResourceReadonlyFromJSON(json: any): ResourceReadonly {
    return ResourceReadonlyFromJSONTyped(json, false);
}

export function ResourceReadonlyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceReadonly {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tagList': json['tagList'],
    };
}

export function ResourceReadonlyToJSON(value?: ResourceReadonly | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tagList': value.tagList,
    };
}


